module.exports = class Data1766244247653 {
    name = 'Data1766244247653'

    async up(db) {
        await db.query(`ALTER TABLE "oracle_price" DROP CONSTRAINT "uq_oracle_price_symbol_round"`)
        await db.query(`CREATE TABLE "network" ("id" character varying NOT NULL, "last_epoch" text, "last_epoch_block" text, "total_supply" text, "circulating_supply" text, "bonded_supply" text, "unbonded_supply" text, "unbonded_percentage" text, "bonded_percentage" text, "seat_price" text, "last_epoch_time" text, "inflation_reserve" text, "treasury_fee" text, "min_base_fee" text, "delegation_rate" text, "unbonding_period" text, "initial_inflation_reserve" text, "withholding_threshold" text, "proposer_reward_rate" text, "oracle_reward_rate" text, "withheld_rewards_pool" text, "treasury_account" text, "elasticity_multiplier" text, "accountability_contract" text, "oracle_contract" text, "acu_contract" text, "supply_control_contract" text, "stabilization_contract" text, "upgrade_manager_contract" text, "inflation_controller_contract" text, "omission_accountability_contract" text, "auctioneer_contract" text, "operator_account" text, "epoch_period" text, "block_period" text, "committee_size" text, "max_schedule_duration" text, "gas_limit" text, "gas_limit_bound_divisor" text, "clustering_threshold" text, "contract_version" text, CONSTRAINT "PK_8f8264c2d37cbbd8282ee9a3c97" PRIMARY KEY ("id"))`)
        await db.query(`DROP INDEX "public"."IDX_5509c1971a61a77c3dd8885ac3"`)
        await db.query(`ALTER TABLE "autonity_event" DROP COLUMN "block_number"`)
        await db.query(`ALTER TABLE "autonity_event" ADD "block_number" numeric NOT NULL`)
        await db.query(`ALTER TABLE "autonity_event" DROP COLUMN "epoch"`)
        await db.query(`ALTER TABLE "autonity_event" ADD "epoch" numeric`)
        await db.query(`DROP INDEX "public"."IDX_19391af85d1833d799e42c1de3"`)
        await db.query(`ALTER TABLE "autonity_event" DROP COLUMN "timestamp"`)
        await db.query(`ALTER TABLE "autonity_event" ADD "timestamp" numeric NOT NULL`)
        await db.query(`DROP INDEX "public"."IDX_939cdbb307f0f043f3b25499f1"`)
        await db.query(`ALTER TABLE "oracle_price" DROP COLUMN "round"`)
        await db.query(`ALTER TABLE "oracle_price" ADD "round" numeric NOT NULL`)
        await db.query(`ALTER TABLE "oracle_price" ALTER COLUMN "price" TYPE numeric`)
        await db.query(`DROP INDEX "public"."IDX_a77ac6d79f0929522f5a1aefcb"`)
        await db.query(`ALTER TABLE "oracle_price" DROP COLUMN "timestamp"`)
        await db.query(`ALTER TABLE "oracle_price" ADD "timestamp" numeric NOT NULL`)
        await db.query(`CREATE INDEX "IDX_5509c1971a61a77c3dd8885ac3" ON "autonity_event" ("block_number") `)
        await db.query(`CREATE INDEX "IDX_19391af85d1833d799e42c1de3" ON "autonity_event" ("timestamp") `)
        await db.query(`CREATE INDEX "IDX_939cdbb307f0f043f3b25499f1" ON "oracle_price" ("round") `)
        await db.query(`CREATE INDEX "IDX_a77ac6d79f0929522f5a1aefcb" ON "oracle_price" ("timestamp") `)
    }

    async down(db) {
        await db.query(`ALTER TABLE "oracle_price" ADD CONSTRAINT "uq_oracle_price_symbol_round" UNIQUE ("symbol", "round")`)
        await db.query(`DROP TABLE "network"`)
        await db.query(`CREATE INDEX "IDX_5509c1971a61a77c3dd8885ac3" ON "autonity_event" ("block_number") `)
        await db.query(`ALTER TABLE "autonity_event" ADD "block_number" bigint NOT NULL`)
        await db.query(`ALTER TABLE "autonity_event" DROP COLUMN "block_number"`)
        await db.query(`ALTER TABLE "autonity_event" ADD "epoch" bigint`)
        await db.query(`ALTER TABLE "autonity_event" DROP COLUMN "epoch"`)
        await db.query(`CREATE INDEX "IDX_19391af85d1833d799e42c1de3" ON "autonity_event" ("timestamp") `)
        await db.query(`ALTER TABLE "autonity_event" ADD "timestamp" bigint NOT NULL`)
        await db.query(`ALTER TABLE "autonity_event" DROP COLUMN "timestamp"`)
        await db.query(`CREATE INDEX "IDX_939cdbb307f0f043f3b25499f1" ON "oracle_price" ("round") `)
        await db.query(`ALTER TABLE "oracle_price" ADD "round" bigint NOT NULL`)
        await db.query(`ALTER TABLE "oracle_price" DROP COLUMN "round"`)
        await db.query(`ALTER TABLE "oracle_price" ALTER COLUMN "price" TYPE numeric(36,18)`)
        await db.query(`CREATE INDEX "IDX_a77ac6d79f0929522f5a1aefcb" ON "oracle_price" ("timestamp") `)
        await db.query(`ALTER TABLE "oracle_price" ADD "timestamp" bigint NOT NULL`)
        await db.query(`ALTER TABLE "oracle_price" DROP COLUMN "timestamp"`)
        await db.query(`DROP INDEX "public"."IDX_5509c1971a61a77c3dd8885ac3"`)
        await db.query(`DROP INDEX "public"."IDX_19391af85d1833d799e42c1de3"`)
        await db.query(`DROP INDEX "public"."IDX_939cdbb307f0f043f3b25499f1"`)
        await db.query(`DROP INDEX "public"."IDX_a77ac6d79f0929522f5a1aefcb"`)
    }
}
